name: bumpDocker
on:
  workflow_dispatch:
    inputs:
      bumpAmount:
        description: Bump amount
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  bump:
    permissions:
      contents: write
    uses: jaid/workflows/.github/workflows/bump.yml@main
    with:
      bumpAmount: ${{ inputs.bumpAmount }}
  pushDocker:
    name: Docker image ${{ matrix.flavorSuffix }}
    permissions:
      packages: write
      contents: read
    needs:
      - bump
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu:rolling
            pythonPackageVersion: 3.11
          - flavorSuffix: lts
            image: ubuntu:latest
            pythonPackageVersion: 3.11
          - flavorSuffix: debian
            image: debian:stable-slim
            pythonPackageVersion: 3.9
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      dockerHubUser: jaidchen
      buildArgs: |
        image=${{ matrix.image }}
        pythonPackageVersion=${{ matrix.pythonPackageVersion }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
      arch: linux/amd64,linux/arm64/v8
      versionTag: ${{ needs.bump.outputs.newSemver }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
