name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  matrix:
    name: Testing
    uses: jaid/workflows/.github/workflows/makeDockerTagMatrix.yml@main
    with:
      bases: ubuntu:rolling ubuntu:latest debian:stable-slim
      platform: linux/amd64 linux/arm64/v8
      additionEvals: |
        pythonVersion: base.startsWith('debian') ? '3.9' : '3.11'
  test:
    name: Test Docker
    needs:
      - matrix
    permissions:
      contents: read
    uses: jaid/workflows/.github/workflows/testDocker.yml@main
    with:
      test: /\+0+\s+\.cargo/.test(stdout)
      buildArgs: |
        pythonPackageVersion=3.11
  pushDocker:
    needs:
      - test
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.output) }}
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      dockerHubUser: jaidchen
      arch: ${{ matrix.platform }}
      buildArgs: |
        image=${{ matrix.base }}
        pythonPackageVersion=${{ matrix.pythonVersion }}
      flavorSuffix: ${{ matrix.id }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
