name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  matrix:
    uses: jaid/workflows/.github/workflows/makeDockerTagMatrix.yml@main
    with:
      bases: ubuntu:rolling ubuntu:latest debian:stable-slim
      platform: linux/amd64 linux/arm64/v8
      additionEvals: |
        pythonVersion: Object.create({ 'debian:stable-slim': '3.9' })[base] ?? '3.11'
        javaVersion: Object.create({ 'ubuntu:rolling': '21', 'ubuntu:latest': '19' })[base] ?? '17'
  test:
    name: test${{ matrix.id && format(' ({0})', matrix.id) }}
    needs:
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.output) }}
    permissions:
      contents: read
    uses: jaid/workflows/.github/workflows/testDocker.yml@main
    with:
      test: /\+0+\s+\.cargo/.test(stdout)
      buildArgs: |
        image=${{ matrix.base }}
        pythonPackageVersion=${{ matrix.pythonVersion }}
        javaVersion=${{ matrix.javaVersion }}
      arch: ${{ matrix.platform }}
  pushDocker:
    name: push${{ matrix.id && format(' ({0})', matrix.id) }}
    needs:
      - test
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.output) }}
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      dockerHubUser: jaidchen
      arch: ${{ matrix.platform }}
      buildArgs: |
        image=${{ matrix.base }}
        pythonPackageVersion=${{ matrix.pythonVersion }}
        javaVersion=${{ matrix.javaVersion }}
      flavorSuffix: ${{ matrix.id }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
