name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  job:
    strategy:
      matrix:
        include:
          - flavorSuffix: debian
            image: debian:stable-slim
            arch: linux/amd64
          - flavorSuffix: debian2
            image: debian:stable-slim
            arch: linux/arm/v5
          - flavorSuffix: debian3
            image: debian:stable-slim
            arch: linux/arm/v7
          - flavorSuffix: debian4
            image: debian:stable-slim
            arch: linux/arm64/v8
          - flavorSuffix: debian5
            image: debian:stable-slim
            arch: linux/ppc64le
          - flavorSuffix: debian6
            image: debian:stable-slim
            arch: linux/s390x
          # - flavorSuffix: ''
          #   image: ubuntu:rolling
          #   arch: ''
          # - flavorSuffix: ubuntu-latest
          #   image: ubuntu:latest
          #   arch: ''
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      buildArgs: image=${{ matrix.image }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
      arch: ${{ matrix.arch }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
