name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
  repository_dispatch:
    types: [bumped]
jobs:
  debug:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  job:
    name: ${{ github.workflow }}
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    permissions:
      contents: read
      packages: write
    with:
      dockerHubUser: jaidchen
      matrixPlatform: linux/amd64 linux/arm64/v8
      matrixBases: ubuntu:rolling ubuntu:latest debian:stable-slim
      matrixAdditionEvals: |-
        pythonVersion: Object.create({ 'debian:stable-slim': '3.9' })[base] ?? '3.12'
        javaVersion: Object.create({ 'ubuntu:rolling': '21', 'ubuntu:latest': '19' })[base] ?? '17'
        nodeVersion: current
      # matrixFlavorEval: |-
      #   const baseSegment = base === 'a' ? false : base
      #   const platformSegment = platformShortcuts[platform] ?? platform.replaceAll('/', '_');
      #   [baseSegment, platformSegment].filter(part => part?.length).join('-')
      testEval: stdout.includes(':-):)')  && stdout.includes('Min [ms]')
      versionTag: ${{ github.event.client_payload.newTag }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}