name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavorSuffix: debian
            image: debian:stable-slim
          - image: ubuntu:rolling
          - flavorSuffix: lts
            image: ubuntu:latest
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      buildArgs: |
        image=${{ matrix.image }}
        flavorSuffix=${{ matrix.flavorSuffix }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
